FROM ankane/pgvector:v0.4.4

ARG POSTGRES_PASSWORD POSTGRES_USER POSTGRES_DB

ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_DB=$POSTGRES_DB

COPY ./add-vector-extension.sql /docker-entrypoint-initdb.d/
